// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_O5cN-SXamRQXyoilOY3R6JvL6wSmTU',
    appId: '1:68080006856:web:dfa8b04979598d4b6257fd',
    messagingSenderId: '68080006856',
    projectId: 'ai-image-b30e6',
    authDomain: 'ai-image-b30e6.firebaseapp.com',
    databaseURL: 'https://ai-image-b30e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-b30e6.firebasestorage.app',
    measurementId: 'G-641L307R02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2gGrUenK0pP9ceqAIGHpoi92rkLU8RwM',
    appId: '1:68080006856:android:323034e1e53ce7f96257fd',
    messagingSenderId: '68080006856',
    projectId: 'ai-image-b30e6',
    databaseURL: 'https://ai-image-b30e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-b30e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpThcxz2_dDU0Chz8JwgfK2BzBgf6ctY',
    appId: '1:68080006856:ios:57574e1fdd9724bb6257fd',
    messagingSenderId: '68080006856',
    projectId: 'ai-image-b30e6',
    databaseURL: 'https://ai-image-b30e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-b30e6.firebasestorage.app',
    iosBundleId: 'com.example.aiImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpThcxz2_dDU0Chz8JwgfK2BzBgf6ctY',
    appId: '1:68080006856:ios:57574e1fdd9724bb6257fd',
    messagingSenderId: '68080006856',
    projectId: 'ai-image-b30e6',
    databaseURL: 'https://ai-image-b30e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-b30e6.firebasestorage.app',
    iosBundleId: 'com.example.aiImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc_O5cN-SXamRQXyoilOY3R6JvL6wSmTU',
    appId: '1:68080006856:web:fc926a695a99b80c6257fd',
    messagingSenderId: '68080006856',
    projectId: 'ai-image-b30e6',
    authDomain: 'ai-image-b30e6.firebaseapp.com',
    databaseURL: 'https://ai-image-b30e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-b30e6.firebasestorage.app',
    measurementId: 'G-YYVDM90LLB',
  );
}
